# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build and publish artifact

on:
  push:
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Extract tag from the reference
      run: ZOLARA_GIT_TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
    
    - name: Build with tag
      run: go build -a -installsuffix cgo -o library-${{ ZOLARA_GIT_TAG }}.tar.gz .

    - name: Upload artifact with tag
      uses: actions/upload-artifact@v4
      with:
        name: library-${{ ZOLARA_GIT_TAG }}
        path: library-${{ ZOLARA_GIT_TAG }}.tar.gz